services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
        environment:
            discovery.type: single-node
            xpack.security.enabled: 'false'
            cluster.routing.allocation.disk.threshold_enabled: 'false'
        ports:
            - "9200:9200"
        healthcheck:
            test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
            interval: 5s
            timeout: 5s
            retries: 20
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data

volumes:
    elasticsearch-data:
