modelflow_ai:
    providers:
        openai:
            enabled: true
            credentials:
                api_key: "%env(OPENAI_API_KEY)%"
        mistral:
            enabled: true
            credentials:
                api_key: "%env(MISTRAL_API_KEY)%"
        ollama:
            enabled: true
            url: "%env(OLLAMA_URL)%"

    adapters:
        gpt4:
            enabled: true
        gpt3.5:
            enabled: true
        mistral_tiny:
            enabled: true
        mistral_small:
            enabled: true
        mistral_medium:
            enabled: true
        llama2:
            enabled: true
        nexusraven:
            enabled: true
        llava:
            enabled: true

    embeddings:
        generators:
            app.openai_embeddings_generator:
                enabled: true
                provider: "openai"
                model: "text-embedding-ada-002"
                splitter:
                    max_length: 1000
                    separator: " "
                cache:
                    enabled: true
                    cache_pool: cache.app

    experts:
        seo:
            name: SEO-Expert
            description: Expert for SEO
            instructions: |
                You are an SEO expert tasked with analyzing the content of a webpage and generating crucial SEO information to enhance its visibility and searchability online. Your analysis and recommendations will be structured according to a specific JSON schema designed for SEO information, which includes the webpage's title, a brief description, and relevant keywords.
                
                Given the content of a webpage, your role is to:
                    
                    1. Identify the most relevant and impactful title that accurately reflects the core subject or theme of the webpage. This title should be optimized for SEO, making it compelling for both search engines and potential visitors.
                    
                    2. Craft a concise, engaging description of the webpage's content. This description should summarize the webpage in a way that is informative and appealing, highlighting the unique value or information it provides.
                    
                    3. Generate a list of keywords that are closely related to the webpage's content. These keywords should be specific and targeted, representing the primary topics or themes discussed on the page. They play a crucial role in improving the webpage's search engine rankings for those terms.
            criteria:
                - !php/const ModelflowAi\Integration\Symfony\Criteria\ProviderCriteria::OLLAMA
            response_format:
                type: json_schema
                schema:
                    type: object
                    properties:
                        title:
                            type: string
                            description: 'The title of the webpage, important for SEO and the browser tab'
                            required: true
                        description:
                            type: string
                            description: 'A brief description of the webpage content, important for search engine listings'
                            required: true
                        keywords:
                            type: array
                            description: 'A list of keywords relevant to the webpage content'
                            items:
                                type: string
                    required: [ 'title', 'description' ]


    chat:
        adapters:
            - gpt4
            - gpt3.5
            - mistral_tiny
            - mistral_small
            - mistral_medium
            - llama2
            - nexusraven
            - llava

    text:
        adapters:
            - llama2
            - nexusraven
            - llava
