title: Experts
description: This Package is part of the ModelflowAI project. It provides a set of tools for so called experts.
    Comparable with [OpenAIs GPTs](https://openai.com/blog/introducing-gpts) or [Open GPTs](https://www.opengpts.org/).
shortDescription: It provides a set of tools for so called experts comparable to OpenAI GPTs or OpenGPTs.
