name: Quality Assurance

on:
    pull_request_target:
    push:
        branches:
            - '[0-9]+.[0-9]+'

jobs:
    api-client:
        name: Api-Client
        uses: ./.github/workflows/test.yml
        with:
            directory: 'packages/api-client'
            docker: false

    core:
        name: Core
        uses: ./.github/workflows/test.yml
        with:
            directory: 'packages/core'
            docker: false

    elasticsearch-embeddings-store:
        name: Elasticsearch Embeddings Store
        uses: ./.github/workflows/test.yml
        with:
            directory: 'packages/elasticsearch-embeddings-store'
            docker: true

    embeddings:
        name: Embeddings
        uses: ./.github/workflows/test.yml
        with:
            directory: 'packages/embeddings'
            docker: false

    experts:
        name: Experts
        uses: ./.github/workflows/test.yml
        with:
            directory: 'packages/experts'
            docker: false

    mistral:
        name: Mistral
        uses: ./.github/workflows/test.yml
        with:
            directory: 'packages/mistral'
            docker: false

    mistral-adapter:
        name: Mistral Adapter
        uses: ./.github/workflows/test.yml
        with:
            directory: 'packages/mistral-adapter'
            docker: false

    ollama:
        name: Ollama
        uses: ./.github/workflows/test.yml
        with:
            directory: 'packages/ollama'
            docker: false

    ollama-adapter:
        name: Ollama Adapter
        uses: ./.github/workflows/test.yml
        with:
            directory: 'packages/ollama-adapter'
            docker: false

    openai-adapter:
        name: OpenAI Adapter
        uses: ./.github/workflows/test.yml
        with:
            directory: 'packages/openai-adapter'
            docker: false

    prompt-template:
        name: Prompt Template
        uses: ./.github/workflows/test.yml
        with:
            directory: 'packages/prompt-template'
            docker: false

    symfony-integration:
        name: Symfony Integration
        uses: ./.github/workflows/test.yml
        with:
            directory: 'integrations/symfony'
            docker: false
